# Generated by Django 4.1 on 2022-08-25 07:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_workhistory_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='job_title',
            new_name='role',
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv.resume'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cv.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_soft_skill', models.BooleanField(blank=True, default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.resume')),
            ],
        ),
    ]
